trigger:
- main

pool:
  name: todopull

variables:
- name: GITHUB_USERNAME
  value: 'nabeelshafqat19'

jobs:
- job: SyncRepos
  steps:
  - checkout: none
  
  - script: |
      @echo off
      if exist "todo-list-app" rmdir /s /q "todo-list-app"
      if exist "todolistpull" rmdir /s /q "todolistpull"
    displayName: 'Clean workspace'

  - script: git clone https://github.com/dockersamples/todo-list-app.git
    displayName: 'Clone source'

  - script: |
      git config --global credential.helper store
      echo https://$(GITHUB_USERNAME):$(GITHUB_PAT)@github.com >> ~/.git-credentials
      
      git clone https://github.com/nabeelshafqat19/todolistpull.git
      xcopy /E /Y /I "todo-list-app\*" "todolistpull\"
      cd todolistpull
      git add .
      git commit -m "Sync: $(Build.BuildNumber) [skip ci]"
      git push origin main
    displayName: 'Push to target'
    env:
      GITHUB_PAT: $(GITHUB_PAT)